language: node_js
node_js:
- '8'
- '9'
- '10'
- '11'
- '12'
- '13'
- '14'
script:
- npm run test:unit
- npm run lint
jobs:
  include:
    - stage: test
    - stage: NPM Release
      node_js: '10'
      deploy:
        provider: npm
        skip_cleanup: true
        on:
          tags: true
        all_branches: true
        email: developer@google.com
